openapi: 3.0.1
info:
  contact:
    email: unity@jpl.nasa.gov
  description: Unity DAPA Process Mapper
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://unity.jpl.nasa.gov/terms/
  title: Unity DAPA Process Mapper
  version: 0.0.1
servers:
- description: Local development server
  url: http://localhost:8080/unity/v0/
paths:
  /collections/{collection_id}/processes:
    get:
      description: Get processes for collection id
      operationId: get_processes_for_collection_id
      parameters:
      - description: id of a collection
        explode: false
        in: path
        name: collection_id
        required: true
        schema:
          $ref: '#/components/schemas/CollectionId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Processes'
          description: Successfully return a list of processors
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse400'
          description: processor not found
      summary: List processes applicable to a collection specified by collection id
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /collections/{collection_id}/processes/time-series:area:
    get:
      description: Get time series for collection id
      operationId: get_time_series_for_collection_id
      parameters:
      - description: id of a collection
        explode: false
        in: path
        name: collection_id
        required: true
        schema:
          $ref: '#/components/schemas/CollectionId'
        style: simple
      - description: bounding box
        explode: false
        in: query
        name: bbox
        required: true
        schema:
          $ref: '#/components/schemas/BoundingBox'
        style: simple
      - description: start and end time
        explode: false
        in: query
        name: datetime
        required: true
        schema:
          $ref: '#/components/schemas/DateTime'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSeries'
          description: Successfully return a time series
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse400'
          description: processor not found
      summary: Get time series by spatial and temporal constraints for a collection
        specified by collection id
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  parameters:
    CollectionId:
      description: id of a collection
      explode: false
      in: path
      name: collection_id
      required: true
      schema:
        $ref: '#/components/schemas/CollectionId'
      style: simple
    BoundingBox:
      description: bounding box
      explode: false
      in: query
      name: bbox
      required: true
      schema:
        $ref: '#/components/schemas/BoundingBox'
      style: simple
    DateTime:
      description: start and end time
      explode: false
      in: query
      name: datetime
      required: true
      schema:
        $ref: '#/components/schemas/DateTime'
      style: simple
  responses:
    "400Error":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InlineResponse400'
      description: Invalid store
    "404Error":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InlineResponse400'
      description: Store not found
  schemas:
    InlineResponse400:
      description: A customized HTTP 400 response which explains why the service cannot
        or will not process the store.
      properties:
        message:
          description: A message to accompany the HTTP 400 response.
          type: string
    CollectionId:
      description: collection id
      example: JPL_MUR25-JPL-L4-GLOB-v04.2
      type: string
    BoundingBox:
      description: bounding box
      example: -160,-15,-130,15
      type: string
    DateTime:
      description: start/end time in iso format
      example: 2022-01-01T00:00:00Z/2022-01-31T23:59:59Z
      type: string
    Processes:
      items:
        type: string
      type: array
    TimeSeries:
      items:
        format: float
        type: number
      type: array
